### PR TITLE
use ordered_float::OrderedFloat & impl From<&ObjHashable> for Obj

### PR DESCRIPTION
**Pull request by OmmyZhang**
This can solve #3 . (please bump version if this is merged

### CODE REVIEW

**Comment by sollyucko** [comment]
Sure, LGTM. Sorry for not noticing for 8 months. Add a version bump (probably major just in case, since the behavior of `hash` does change) and apply the simplification I commented, unless you have any objections, and I'll merge this and publish to crates.io.

**Comment by OmmyZhang** [comment]
@sollyucko  Hi, where is the simplification you commented? Do I miss something? Or maybe your comments are still pending status?

**Comment by sollyucko** [comment]
My review comment is marked Pending. I suggested changing `x.inner().iter().cloned().collect()` to `x.inner().clone()`.

**Comment by OmmyZhang** [comment]
> My review comment is marked Pending. I suggested changing `x.inner().iter().cloned().collect()` to `x.inner().clone()`.

Thanks, it's done.

**Comment by sollyucko** [comment]
LGTM. I'll merge now and publish to crates.io tonight. Thanks for contributing, and sorry for the huge delay!

**Comment by sollyucko** [comment]
I've published it to crates.io now! https://crates.io/crates/py-marshal/0.4.0

BTW, does this fix issues #3 and #4?

**Comment by OmmyZhang** [comment]
Yes, this fixes them.

**Pull request merged**
